
const apiList = [
    {
      name: 'numberVerification',
      path: 'number-verification/v0/verify',
      body: '{"phoneNumber": "541141832256"}',
      displayName: 'Number Verification',
      description: 'Verify a phone number.',
      usecase: 'numberVerification',
      scope: 'dpv:FraudPreventionAndDetection#number-verification',
    },
    {
      name: 'retrievePhoneNumber',
      path: 'number-verification/v0/device-phone-number',
      body: '',
      method: 'GET',
      displayName: 'Retrieve Phone Number',
      description: 'Retrieve a phone number from a device.',
      usecase: 'numberVerification',
      scope: 'dpv:FraudPreventionAndDetection#number-verification',
    },
    {
      name: 'deviceStatus',
      path: 'device-status/v0/connectivity',
      body: '{"device": {"phoneNumber": "541141832256"}}',
      displayName: 'Device Status - Connectivity',
      description: 'Obtains the connectivity status of a device.',
      usecase: 'deviceStatus',
      scope: 'dpv:FraudPreventionAndDetection#device-status',
    },
    {
      name: 'deviceStatusRoaming',
      path: 'device-status/v0/roaming',
      body: '{"device": {"phoneNumber": "541141832256"}}',
      displayName: 'Device Status - Roaming',
      description: 'Checks if the device is currently in roaming mode.',
      usecase: 'deviceStatus',
      scope: 'dpv:FraudPreventionAndDetection#device-status',
    },
    {
      name: 'deviceLocationRetrieve',
      path: 'location-retrieval/v0/retrieve',
      body: '{"device": {"phoneNumber": "541141832256"},"maxAge": 60}',
      displayName: 'Device Location - Retrieve',
      description: 'Retrieves the location of a device.',
      usecase: 'deviceLocation',
      scope: 'dpv:FraudPreventionAndDetection#location-retrieval',
    },
    {
      name: 'deviceLocationVerify',
      path: 'location-verification/v0/verify',
      body: '{"device": {"phoneNumber": "541141832256"},"area": {"areaType": "CIRCLE","center": {"latitude": 50.60,"longitude": 50.735851},"radius": 50000}}',
      displayName: 'Device Location - Verify',
      description: 'Verifies the location of a device.',
      usecase: 'deviceLocation',
      scope: 'dpv:FraudPreventionAndDetection#location-verification',
    },
    {
      name: 'simSwap',
      path: 'sim-swap/v0/retrieve-date',
      body: '{"phoneNumber": "543462641443"}',
      displayName: 'SIM Swap',
      description: 'Retrieve SIM swap date',
      usecase: 'simSwap',
      scope: 'dpv:FraudPreventionAndDetection#sim-swap',
    },
    {
      name: "simSwapCheck",
      path: "sim-swap/v0/check",
      body: '{"phoneNumber": "543462641443"}',
      displayName: "SIM Swap Check",
      description: "Checks if SIM swap has been performed during a past period of time.",
      usecase: 'simSwap',
      scope: 'dpv:FraudPreventionAndDetection#sim-swap',
    }
  ];

export default apiList;