
const apiList = [
    {
      name: 'numberVerification',
      path: 'number-verification/v0/verify',
      body: '{"phoneNumber": "541141832256"}',
      displayName: 'Number Verification',
      description: 'Verifica un número de telefono.',
      usecase: 'numberVerification',
    },
    {
      name: 'retrievePhoneNumber',
      path: 'number-verification/v0/device-phone-number',
      body: '',
      method: 'GET',
      displayName: 'Retrieve Phone Number',
      description: 'Recupera el número de telefono.',
      usecase: 'numberVerification',
    },
    {
      name: 'deviceStatus',
      path: 'device-status/v0/connectivity',
      body: '{"device": {"phoneNumber": "541141832256"}}',
      displayName: 'Device Status - Connectivity',
      description: 'Obtiene el estado actual de un dispositivo.',
      usecase: 'deviceStatus',
    },
    {
      name: 'deviceStatusRoaming',
      path: 'device-status/v0/roaming',
      body: '{"device": {"phoneNumber": "541141832256"}}',
      displayName: 'Device Status - Roaming',
      description: 'Obtiene el estado actual de un dispositivo.',
      usecase: 'deviceStatus',
    },
    {
      name: 'deviceLocationRetrieve',
      path: 'location-retrieval/v0/retrieve',
      body: '{"device": {"phoneNumber": "541141832256"},"maxAge": 60}',
      displayName: 'Device Location - Retrieve',
      description: 'Recupera la ubicación actual de un dispositivo.',
      usecase: 'deviceLocation',
    },
    {
      name: 'deviceLocationVerify',
      path: 'location-verification/v0/verify',
      body: '{"device": {"phoneNumber": "541141832256"},"area": {"areaType": "CIRCLE","center": {"latitude": 50.60,"longitude": 50.735851},"radius": 50000}}',
      displayName: 'Device Location - Verify',
      description: 'Valida la ubicación actual de un dispositivo.',
      usecase: 'deviceLocation',
    },
    {
      name: 'simSwap',
      path: 'sim-swap/v0/retrieve-date',
      body: '{"phoneNumber": "543462641443"}',
      displayName: 'SIM Swap',
      description: 'Retrieve SIM swap date',
      usecase: 'simSwap',
    },
    {
      name: "simSwapCheck",
      path: "sim-swap/v0/check",
      body: '{"phoneNumber": "543462641443"}',
      displayName: "SIM Swap Check",
      description: "Checks if SIM swap has been performed during a past period of time.",
      usecase: 'simSwap',
    },
    {
      name: "queryConsent",
      path: "consent/v0/query",
      body: '',
      displayName: "Query Consent",
      description: "Retrieve the details of the consent given by the user to a specific clientId.",
      method: 'GET',
      usecase: 'consent',
    },
    {
      name: "revokeConsent",
      path: "/consent/v0/revoke",
      body: '',
      displayName: "Revoke Consent",
      description: "Revoke the consent previously given by the user to a specific clientId.",
      method: 'DELETE',
      usecase: 'consent',
    }
  ];

export default apiList;