export const scopeOptions = [
    'dpv:FraudPreventionAndDetection#device-status',
    'dpv:FraudPreventionAndDetection#location-verification',
    'dpv:FraudPreventionAndDetection#location-retrieval',
    'dpv:FraudPreventionAndDetection#number-verification',
    'dpv:FraudPreventionAndDetection#sim-swap',
    'dpv:FraudPreventionAndDetection#kyc-match',
    'dpv:FraudPreventionAndDetection#kyc-fill-in',
    'dpv:FraudPreventionAndDetection#device-swap',
    'dpv:FraudPreventionAndDetection#quality-on-demand',
    'dpv:FraudPreventionAndDetection#qos-provisioning',
];

export const environments = {
    development: {
      auth: 'https://opengw.dev.openxpand.com',
      api: 'https://api.dev.openxpand.com/api/camara',
      //api: 'http://localhost:9091/api/camara',
      portal: 'https://developer.dev.openxpand.com/developer/es/:tenant',
    },
    testing: {
      auth: 'https://opengw.test.openxpand.com',
      api: 'https://api.test.openxpand.com/api/camara',
      portal: 'https://developer.test.openxpand.com/developer/es/:tenant',
    },
    production: {
      auth: 'https://opengw.openxpand.com',
      api: 'https://api.openxpand.com/api/camara',
      portal: 'https://developer.openxpand.com/developer/es/:tenant',
    },
  };


export const apiList = [
    {
      name: 'numberVerification',
      title: 'Number Verification',
      path: 'number-verification/v0/verify',
      body: '{"phoneNumber": "541141832256"}',
      displayName: 'Verify',
      description: 'Verify a phone number.',
      usecase: 'numberVerification',
      scope: 'dpv:FraudPreventionAndDetection#number-verification',
    },
    {
      name: 'retrievePhoneNumber',
      title: 'Number Verification',
      path: 'number-verification/v0/device-phone-number',
      body: '',
      method: 'GET',
      displayName: 'Device Phone Number',
      description: 'Retrieve a phone number from a device.',
      usecase: 'numberVerification',
      scope: 'dpv:FraudPreventionAndDetection#number-verification',
    },
    {
      name: 'deviceStatus',
      title: 'Device Status',
      path: 'device-status/v0/connectivity',
      body: '{"device": {"phoneNumber": "541141832256"}}',
      displayName: 'Connectivity',
      description: 'Obtains the connectivity status of a device.',
      usecase: 'deviceStatus',
      scope: 'dpv:FraudPreventionAndDetection#device-status',
    },
    {
      name: 'deviceStatusRoaming',
      title: 'Device Status',
      path: 'device-status/v0/roaming',
      body: '{"device": {"phoneNumber": "541141832256"}}',
      displayName: 'Roaming',
      description: 'Checks if the device is currently in roaming mode.',
      usecase: 'deviceStatus',
      scope: 'dpv:FraudPreventionAndDetection#device-status',
    },
    {
      name: 'deviceLocationRetrieve',
      title: 'Device Location',
      path: 'location-retrieval/v0/retrieve',
      body: '{"device": {"phoneNumber": "541141832256"},"maxAge": 60}',
      displayName: 'Retrieve',
      description: 'Retrieves the location of a device.',
      usecase: 'deviceLocation',
      scope: 'dpv:FraudPreventionAndDetection#location-retrieval',
    },
    {
      name: 'deviceLocationVerify',
      title: 'Device Location',
      path: 'location-verification/v0/verify',
      body: '{"device": {"phoneNumber": "541141832256"},"area": {"areaType": "CIRCLE","center": {"latitude": 50.60,"longitude": 50.735851},"radius": 50000}}',
      displayName: 'Verify',
      description: 'Verifies the location of a device.',
      usecase: 'deviceLocation',
      scope: 'dpv:FraudPreventionAndDetection#location-verification',
    },
    {
      name: 'simSwap',
      title: 'SIM Swap',
      path: 'sim-swap/v0/retrieve-date',
      body: '{"phoneNumber": "543462641443"}',
      displayName: 'Retrieve Date',
      description: 'Retrieve SIM swap date',
      usecase: 'simSwap',
      scope: 'dpv:FraudPreventionAndDetection#sim-swap',
    },
    {
      name: "simSwapCheck",
      title: 'SIM Swap',
      path: "sim-swap/v0/check",
      body: '{"phoneNumber": "543462641443"}',
      displayName: "Check",
      description: "Checks if SIM swap has been performed during a past period of time.",
      usecase: 'simSwap',
      scope: 'dpv:FraudPreventionAndDetection#sim-swap',
    },
    {
      name: "kycMatchv0.3",
      title: 'KYC Match v0.3',
      path: "kyc-match/v0.3/match",
      body: '{"phoneNumber":"1111110068","idDocument":"23780766","name":"Javier Ampudia De Vera","givenName":"Javier","familyName":"Ampudia De Vera","nameKanaHankaku":null,"nameKanaZenkaku":null,"middleNames":null,"familyNameAtBirth":null,"address":"MITRE 705","streetName":"MITRE","streetNumber":"705","postalCode":"8000","region":"","locality":"","country":"Argentina","houseNumberExtension":"","birthdate":"1974-01-12","email":"autogestion@gmail.com","gender":"Masculino","floor":"","departament":""}',
      displayName: "Know Your Customer Match",
      description: "Know Your Customer Match",
      usecase: 'kycMatch',
      scope: 'dpv:FraudPreventionAndDetection#kyc-match',
    },
    {
      name: "kycFillIn",
      title: 'KYC Fill In',
      path: "kyc-fill-in/v0.3/fill-in",
      body: '{"phoneNumber": "543462641443"}',
      displayName: "Know Your Customer Fill In",
      description: "Know Your Customer Fill In",
      usecase: 'kycFillIn',
      scope: 'dpv:FraudPreventionAndDetection#kyc-fill-in',
    },
    {
      name: "deviceSwapRetrieve",
      title: 'Device Swap',
      path: 'device-swap/v0.2/retrieve-date',
      body: '{"phoneNumber": "+346661113334"}',
      displayName: "Retrieve Date",
      description: "Device Swap Retrieve Date",
      usecase: 'deviceSwap',
      scope: 'dpv:FraudPreventionAndDetection#device-swap',
    },
    {
      name: "deviceSwapCheck",
      title: 'Device Swap',
      path: 'device-swap/v0.2/check',
      body: '{"phoneNumber": "+346661113334","maxAge": 120}',
      displayName: "Check",
      description: "Device Swap Check",
      usecase: 'deviceSwap',
      scope: 'dpv:FraudPreventionAndDetection#device-swap',
    },
    {
      name: "qualityOnDemandSession",
      title: 'Quality On Demand',
      path: 'quality-on-demand/v1/sessions',
      body: '{"device": {"phoneNumber": "+123456789","networkAccessIdentifier": "123456789@domain.com","ipv4Address": {"publicAddress": "203.0.113.0","publicPort": 59765},"ipv6Address": "2001:db8:85a3:8d3:1319:8a2e:370:7344"  },  "applicationServer": {    "ipv4Address": "198.51.100.0/24",    "ipv6Address": "2001:db8:85a3:8d3:1319:8a2e:370:7344"  },  "devicePorts": {    "ranges": [{"from": 5010,        "to": 5020      }],    "ports": [      5060,5070]},"applicationServerPorts": {"ranges": [{"from": 5010,"to": 5020}],"ports": [5060,5070]},"qosProfile": "voice","sink": "https://endpoint.example.com/sink","sinkCredential": {"credentialType": "PLAIN"},"duration": 3600}',
      displayName: "Session",
      description: "Quality On Demand Session",
      usecase: 'qualityOnDemand',
      scope: 'dpv:FraudPreventionAndDetection#quality-on-demand',
    },
    {
      name: "qualityOnDemandRetrieveSession",
      title: 'Quality On Demand',
      path: 'quality-on-demand/v1/retrieve-sessions',
      body: '{"device": {"phoneNumber": "+123456789","networkAccessIdentifier": "123456789@domain.com","ipv4Address": {"publicAddress": "203.0.113.0","publicPort": 59765},"ipv6Address": "2001:db8:85a3:8d3:1319:8a2e:370:7344"}}',
      displayName: "Retrieve",
      description: "Quality On Demand Retrieve Session",
      usecase: 'qualityOnDemand',
      scope: 'dpv:FraudPreventionAndDetection#quality-on-demand',
    },
    {
      name: "qosProvisioningCreate",
      title: 'QoS Provisioning',
      path: 'qos-provisioning/v1/qos-assignments',
      body: '{"device": {"phoneNumber": "+123456789","networkAccessIdentifier": "123456789@domain.com","ipv4Address": {"publicAddress": "203.0.113.0","publicPort": 59765},"ipv6Address": "2001:db8:85a3:8d3:1319:8a2e:370:7344"},"qosProfile": "QCI_1_voice","sink": "https://endpoint.example.com/sink","sinkCredential": {}}',
      displayName: "Create QoS Assignment",
      description: "Create a new QoS assignment",
      usecase: 'qosProvisioning',
      scope: 'dpv:FraudPreventionAndDetection#qos-provisioning',
    },
    {
      name: "qosProvisioningRetrieve",
      title: 'QoS Provisioning',
      path: 'qos-provisioning/v1/qos-assignments/{sessionId}',
      body: '',
      method: 'GET',
      displayName: "Retrieve QoS Assignment",
      description: "Retrieve a QoS assignment by ID",
      usecase: 'qosProvisioning',
      scope: 'dpv:FraudPreventionAndDetection#qos-provisioning',
    },
    {
      name: "qosProvisioningDelete",
      title: 'QoS Provisioning',
      path: 'qos-provisioning/v1/qos-assignments/{sessionId}',
      body: '',
      method: 'DELETE',
      displayName: "Delete QoS Assignment",
      description: "Delete a QoS assignment by ID",
      usecase: 'qosProvisioning',
      scope: 'dpv:FraudPreventionAndDetection#qos-provisioning',
    },
  ];

export const steps = [
    {
      title: "Step 1:",
      description: "Authorization code request (GET: user-side)",
      url: `:host/auth/realms/:tenant/protocol/openid-connect/auth?response_type=code&client_id=:clientId&redirect_uri=https://openxpand-kc.vercel.app/api/callback&scope=:scope&prompt=none`,
      method: "GET"
    },
    {
      title: "Step 2:",
      description: "Token request with authorization code (POST: client-side)",
      url: `:host/auth/realms/:tenant/protocol/openid-connect/token`,
      method: "POST",
      headers: 'Content-Type: application/x-www-form-urlencoded',
      body: `grant_type=authorization_code&code=:code&redirect_uri=https://openxpand-kc.vercel.app/api/callback&client_id=:clientId&client_secret=:clientSecret`,
    },
];
