export const environments = {
    development: {
      auth: 'https://opengw.dev.openxpand.com',
      api: 'https://api.dev.openxpand.com/api/camara',
      //api: 'http://localhost:9091/api/camara',
      portal: 'https://developer.dev.openxpand.com/developer/es/:tenant',
    },
    testing: {
      auth: 'https://opengw.test.openxpand.com',
      api: 'https://api.test.openxpand.com/api/camara',
      portal: 'https://developer.test.openxpand.com/developer/es/:tenant',
    },
    production: {
      auth: 'https://opengw.openxpand.com',
      api: 'https://api.openxpand.com/api/camara',
      portal: 'https://developer.openxpand.com/developer/es/:tenant',
    },
  };


export const apiList = [
    {
      name: 'numberVerification',
      title: 'Number Verification',
      path: 'number-verification/v0/verify',
      body: '{"phoneNumber": "541141832256"}',
      displayName: 'Verify',
      description: 'Verify a phone number.',
      usecase: 'numberVerification',
      versionId: 'number-verification/v0',
      scopes: ['dpv:FraudPreventionAndDetection#number-verification', 'number-verification:verify'],
    },
    {
      name: 'retrievePhoneNumber',
      title: 'Number Verification',
      path: 'number-verification/v0/device-phone-number',
      body: '',
      method: 'GET',
      displayName: 'Device Phone Number',
      description: 'Retrieve a phone number from a device.',
      usecase: 'numberVerification',
      versionId: 'number-verification/v0',
      scopes: ['dpv:FraudPreventionAndDetection#number-verification', 'number-verification:device-phone-number:read'],
    },
    {
      name: 'deviceStatus',
      title: 'Device Status',
      path: 'device-status/v0/connectivity',
      body: '{"device": {"phoneNumber": "541141832256"}}',
      displayName: 'Connectivity',
      description: 'Obtains the connectivity status of a device.',
      usecase: 'deviceStatus',
      versionId: 'device-status/v0',
      scopes: ['dpv:FraudPreventionAndDetection#device-status'],
    },
    {
      name: 'deviceStatusRoaming',
      title: 'Device Status',
      path: 'device-status/v0/roaming',
      body: '{"device": {"phoneNumber": "541141832256"}}',
      displayName: 'Roaming',
      description: 'Checks if the device is currently in roaming mode.',
      usecase: 'deviceStatus',
      versionId: 'device-status/v0',
      scopes: ['dpv:FraudPreventionAndDetection#device-status'],
    },
    {
      name: 'deviceStatusV1',
      title: 'Device Status',
      path: 'device-status/v1/connectivity',
      body: '{"device": {"phoneNumber": "+541141832256"}}',
      displayName: 'Connectivity v1',
      description: 'Connectivity status (v1). Requires scope device-status:connectivity:read.',
      usecase: 'deviceStatus',
      versionId: 'device-status/v1',
      scopes: ['device-status:connectivity:read'],
    },
    {
      name: 'deviceStatusRoamingV1',
      title: 'Device Status',
      path: 'device-status/v1/roaming',
      body: '{"device": {"phoneNumber": "+541141832256"}}',
      displayName: 'Roaming v1',
      description: 'Roaming status (v1). Requires scope device-status:roaming:read.',
      usecase: 'deviceStatus',
      versionId: 'device-status/v1',
      scopes: ['device-status:roaming:read'],
    },
    {
      name: 'deviceReachabilityStatus',
      title: 'Device Reachability Status',
      path: 'device-reachability-status/v1/retrieve',
      body: '{"device": {"phoneNumber": "+541141832256"}}',
      displayName: 'Retrieve',
      description: 'Retrieves whether the device is reachable (DATA / SMS).',
      usecase: 'deviceReachabilityStatus',
      versionId: 'device-reachability-status/v1',
      scopes: ['dpv:FraudPreventionAndDetection#device-reachability-status', 'device-reachability-status:read'],
    },
    {
      name: 'deviceRoamingStatus',
      title: 'Device Roaming Status',
      path: 'device-roaming-status/v1/retrieve',
      body: '{"device": {"phoneNumber": "+541141832256"}}',
      displayName: 'Retrieve',
      description: 'Retrieves roaming status and country for a device.',
      usecase: 'deviceRoamingStatus',
      versionId: 'device-roaming-status/v1',
      scopes: ['dpv:FraudPreventionAndDetection#device-roaming-status', 'device-roaming-status:read'],
    },
    {
      name: 'deviceLocationRetrieve',
      title: 'Device Location',
      path: 'location-retrieval/v0/retrieve',
      body: '{"device": {"phoneNumber": "541140000002"},"maxAge": 60}',
      displayName: 'Retrieve',
      description: 'Retrieves the location of a device.',
      usecase: 'deviceLocation',
      versionId: 'location-retrieval/v0',
      scopes: ['dpv:FraudPreventionAndDetection#location-retrieval'],
    },
    {
      name: 'deviceLocationRetrieveV05',
      title: 'Device Location',
      path: 'location-retrieval/v0.5/retrieve',
      body: '{"device": {"phoneNumber": "+541140000002"},"maxAge": 60,"maxSurface": 2000000}',
      displayName: 'Retrieve v0.5',
      description: 'Location retrieval v0.5 (maxAge, maxSurface). Requires scope location-retrieval:read.',
      usecase: 'deviceLocation',
      versionId: 'location-retrieval/v0.5',
      scopes: ['location-retrieval:read'],
    },
    {
      name: 'deviceLocationVerify',
      title: 'Device Location',
      path: 'location-verification/v0/verify',
      body: '{"device": {"phoneNumber": "541140000002"},"area": {"areaType": "CIRCLE","center": {"latitude": 50.60,"longitude": 50.735851},"radius": 50000}}',
      displayName: 'Verify',
      description: 'Verifies the location of a device.',
      usecase: 'deviceLocation',
      versionId: 'location-verification/v0',
      scopes: ['dpv:FraudPreventionAndDetection#location-verification'],
    },
    {
      name: 'deviceLocationVerifyV3',
      title: 'Device Location',
      path: 'location-verification/v3/verify',
      body: '{"device": {"phoneNumber": "+541140000002"},"area": {"areaType": "CIRCLE","center": {"latitude": 50.60,"longitude": 50.735851},"radius": 50000},"maxAge": 60}',
      displayName: 'Verify v3',
      description: 'Location verification v3. Requires scope location-verification:verify.',
      usecase: 'deviceLocation',
      versionId: 'location-verification/v3',
      scopes: ['location-verification:verify'],
    },
    {
      name: 'simSwap',
      title: 'SIM Swap',
      path: 'sim-swap/v0/retrieve-date',
      body: '{"phoneNumber": "543462641443"}',
      displayName: 'Retrieve Date',
      description: 'Retrieve SIM swap date',
      usecase: 'simSwap',
      versionId: 'sim-swap/v0',
      scopes: ['dpv:FraudPreventionAndDetection#sim-swap'],
    },
    {
      name: "simSwapCheck",
      title: 'SIM Swap',
      path: "sim-swap/v0/check",
      body: '{"phoneNumber": "543462641443"}',
      displayName: "Check",
      description: "Checks if SIM swap has been performed during a past period of time.",
      usecase: 'simSwap',
      versionId: 'sim-swap/v0',
      scopes: ['dpv:FraudPreventionAndDetection#sim-swap'],
    },
    {
      name: "simSwapV2",
      title: 'SIM Swap',
      path: "sim-swap/v2/retrieve-date",
      body: '{"phoneNumber": "+543462641443"}',
      displayName: "Retrieve Date v2",
      description: "SIM swap date (v2). Requires dpv:FraudPreventionAndDetection and sim-swap:retrieve-date.",
      usecase: 'simSwap',
      versionId: 'sim-swap/v2',
      scopes: ['dpv:FraudPreventionAndDetection', 'sim-swap:retrieve-date'],
    },
    {
      name: "simSwapCheckV2",
      title: 'SIM Swap',
      path: "sim-swap/v2/check",
      body: '{"phoneNumber": "+543462641443","maxAge": 240}',
      displayName: "Check v2",
      description: "SIM swap check (v2). Requires dpv:FraudPreventionAndDetection and sim-swap:check.",
      usecase: 'simSwap',
      versionId: 'sim-swap/v2',
      scopes: ['dpv:FraudPreventionAndDetection', 'sim-swap:check'],
    },
    {
      name: "kycMatchv0.3",
      title: 'KYC Match',
      path: "kyc-match/v0.3/match",
      body: '{"phoneNumber":"1111110068","idDocument":"23780766","name":"Javier Ampudia De Vera","givenName":"Javier","familyName":"Ampudia De Vera","nameKanaHankaku":null,"nameKanaZenkaku":null,"middleNames":null,"familyNameAtBirth":null,"address":"MITRE 705","streetName":"MITRE","streetNumber":"705","postalCode":"8000","region":"","locality":"","country":"AR","houseNumberExtension":"","birthdate":"1974-01-12","email":"autogestion@gmail.com","gender":"MALE","floor":"","departament":""}',
      displayName: "Match v0.3",
      description: "Know Your Customer Match v0.3",
      usecase: 'kycMatch',
      versionId: 'kyc-match/v0.3',
      scopes: ['dpv:FraudPreventionAndDetection#kyc-match'],
    },
    {
      name: "kycMatchv0.4",
      title: 'KYC Match',
      path: "kyc-match/v0.4/match",
      body: '{"phoneNumber":"1111110068","idDocument":"23780766","idDocumentType":"passport","idDocumentExpiryDate":"2030-12-31","name":"Javier Ampudia De Vera","givenName":"Javier","familyName":"Ampudia De Vera","nameKanaHankaku":null,"nameKanaZenkaku":null,"middleNames":null,"familyNameAtBirth":null,"address":"MITRE 705","streetName":"MITRE","streetNumber":"705","postalCode":"8000","region":"","locality":"","country":"AR","houseNumberExtension":"","birthdate":"1974-01-12","email":"autogestion@gmail.com","gender":"MALE","cityOfBirth":"Buenos Aires","countryOfBirth":"AR","nationality":"AR"}',
      displayName: "Match v0.4",
      description: "KYC Match v0.4 (document type, birth and nationality). Requires scope kyc-match:match.",
      usecase: 'kycMatch',
      versionId: 'kyc-match/v0.4',
      scopes: ['kyc-match:match'],
    },
    {
      name: "kycFillIn",
      title: 'KYC Fill In',
      path: "kyc-fill-in/v0.3/fill-in",
      body: '{"phoneNumber": "543462641443"}',
      displayName: "Fill In v0.3",
      description: "Know Your Customer Fill In v0.3",
      usecase: 'kycFillIn',
      versionId: 'kyc-fill-in/v0.3',
      scopes: ['dpv:FraudPreventionAndDetection#kyc-fill-in'],
    },
    {
      name: "kycFillInV04",
      title: 'KYC Fill In',
      path: "kyc-fill-in/v0.4/fill-in",
      body: '{"phoneNumber": "+543462641443"}',
      displayName: "Fill In v0.4",
      description: "KYC Fill In v0.4 (extended identity fields). Requires scope kyc-fill-in:fill-in.",
      usecase: 'kycFillIn',
      versionId: 'kyc-fill-in/v0.4',
      scopes: ['kyc-fill-in:fill-in'],
    },
    {
      name: "kycTenure",
      title: 'KYC Tenure',
      path: "kyc-tenure/v0.2/check-tenure",
      body: '{"phoneNumber": "+543462641442", "tenureDate": "2025-01-01"}',
      displayName: "Check Tenure",
      description: "Checks whether the subscriber relationship existed on the specified date.",
      usecase: 'kycTenure',
      versionId: 'kyc-tenure/v0.2',
      scopes: ['dpv:FraudPreventionAndDetection#kyc-tenure', 'kyc-tenure:check-tenure'],
    },
    {
      name: "deviceSwapRetrieve",
      title: 'Device Swap',
      path: 'device-swap/v0.2/retrieve-date',
      body: '{"phoneNumber": "+346661113334"}',
      displayName: "Retrieve Date",
      description: "Device Swap Retrieve Date",
      usecase: 'deviceSwap',
      versionId: 'device-swap/v0.2',
      scopes: ['dpv:FraudPreventionAndDetection#device-swap'],
    },
    {
      name: "deviceSwapCheck",
      title: 'Device Swap',
      path: 'device-swap/v0.2/check',
      body: '{"phoneNumber": "+346661113334","maxAge": 120}',
      displayName: "Check",
      description: "Device Swap Check",
      usecase: 'deviceSwap',
      versionId: 'device-swap/v0.2',
      scopes: ['dpv:FraudPreventionAndDetection#device-swap'],
    },
    {
      name: "deviceSwapRetrieveV1",
      title: 'Device Swap',
      path: 'device-swap/v1/retrieve-date',
      body: '{"phoneNumber": "+346661113334"}',
      displayName: "Retrieve Date v1",
      description: "Device swap date (v1). Requires dpv:FraudPreventionAndDetection and device-swap:retrieve-date.",
      usecase: 'deviceSwap',
      versionId: 'device-swap/v1',
      scopes: ['dpv:FraudPreventionAndDetection', 'device-swap:retrieve-date'],
    },
    {
      name: "deviceSwapCheckV1",
      title: 'Device Swap',
      path: 'device-swap/v1/check',
      body: '{"phoneNumber": "+346661113334","maxAge": 120}',
      displayName: "Check v1",
      description: "Device swap check (v1). Requires dpv:FraudPreventionAndDetection and device-swap:check.",
      usecase: 'deviceSwap',
      versionId: 'device-swap/v1',
      scopes: ['dpv:FraudPreventionAndDetection', 'device-swap:check'],
    },
    {
      name: "qualityOnDemandSession",
      title: 'Quality On Demand',
      path: 'quality-on-demand/v1/sessions',
      body: '{"device": {"phoneNumber": "+123456789","networkAccessIdentifier": "123456789@domain.com","ipv4Address": {"publicAddress": "203.0.113.0","publicPort": 59765},"ipv6Address": "2001:db8:85a3:8d3:1319:8a2e:370:7344"  },  "applicationServer": {    "ipv4Address": "198.51.100.0/24",    "ipv6Address": "2001:db8:85a3:8d3:1319:8a2e:370:7344"  },  "devicePorts": {    "ranges": [{"from": 5010,        "to": 5020      }],    "ports": [      5060,5070]},"applicationServerPorts": {"ranges": [{"from": 5010,"to": 5020}],"ports": [5060,5070]},"qosProfile": "voice","sink": "https://endpoint.example.com/sink","sinkCredential": {"credentialType": "PLAIN"},"duration": 3600}',
      displayName: "Session",
      description: "Quality On Demand Session",
      usecase: 'qualityOnDemand',
      versionId: 'quality-on-demand/v1',
      scopes: ['dpv:FraudPreventionAndDetection#quality-on-demand', 'quality-on-demand:sessions:create'],
    },
    {
      name: "qualityOnDemandRetrieveSession",
      title: 'Quality On Demand',
      path: 'quality-on-demand/v1/retrieve-sessions',
      body: '{"device": {"phoneNumber": "+123456789","networkAccessIdentifier": "123456789@domain.com","ipv4Address": {"publicAddress": "203.0.113.0","publicPort": 59765},"ipv6Address": "2001:db8:85a3:8d3:1319:8a2e:370:7344"}}',
      displayName: "Retrieve",
      description: "Quality On Demand Retrieve Session",
      usecase: 'qualityOnDemand',
      versionId: 'quality-on-demand/v1',
      scopes: ['dpv:FraudPreventionAndDetection#quality-on-demand', 'quality-on-demand:sessions:retrieve-by-device'],
    },
    {
      name: "qosProvisioningCreate",
      title: 'QoS Provisioning',
      path: 'qos-provisioning/v0.3/qos-assignments',
      body: '{"device": { "phoneNumber": "+541130124057"},"qosProfile": "prorizacion_api_qod"}',
      displayName: "Create QoS Assignment",
      description: "Create a new QoS assignment",
      usecase: 'qosProvisioning',
      versionId: 'qos-provisioning/v0.3',
      scopes: ['dpv:FraudPreventionAndDetection#qos-provisioning', 'qos-provisioning:qos-assignments:create'],
    },
    {
      name: "qosProvisioningRetrieve",
      title: 'QoS Provisioning',
      path: 'qos-provisioning/v0.3/qos-assignments/{assignmentId}',
      body: '',
      method: 'GET',
      displayName: "Get QoS Assignment",
      description: "Retrieve a QoS assignment by ID",
      usecase: 'qosProvisioning',
      versionId: 'qos-provisioning/v0.3',
      scopes: ['dpv:FraudPreventionAndDetection#qos-provisioning', 'qos-provisioning:qos-assignments:read'],
    },
    {
      name: "qosProvisioningDelete",
      title: 'QoS Provisioning',
      path: 'qos-provisioning/v0.3/qos-assignments/{assignmentId}',
      body: '',
      method: 'DELETE',
      displayName: "Delete QoS Assignment",
      description: "Delete a QoS assignment by ID",
      usecase: 'qosProvisioning',
      versionId: 'qos-provisioning/v0.3',
      scopes: ['dpv:FraudPreventionAndDetection#qos-provisioning', 'qos-provisioning:qos-assignments:delete'],
    },
    {
      name: "qosProvisioningRetrieveAssignment",
      title: 'QoS Provisioning',
      path: 'telecom/qos-provisioning/v0.3/retrieve-qos-assignment',
      body: '{"device": {"phoneNumber": "+541130124057"}}',
      displayName: "Retrieve QoS Assignment",
      description: "Retrieve QoS assignment for a device",
      usecase: 'qosProvisioning',
      versionId: 'qos-provisioning/v0.3',
      scopes: ['dpv:FraudPreventionAndDetection#qos-provisioning', 'qos-provisioning:qos-assignments:read-by-device'],
    },
    {
      name: "carrierLookup",
      title: 'Carrier Lookup',
      path: 'carrier-lookup/v1/retrieve',
      body: '{"phoneNumber": "543872699999"}',
      displayName: "Retrieve Carrier",
      description: "Retrieve carrier information for a phone number",
      usecase: 'carrierLookup',
      versionId: 'carrier-lookup/v1',
      scopes: ['dpv:FraudPreventionAndDetection#carrier-lookup', 'carrier-lookup:retrieve'],
    },
    {
      name: "qosProfilesRetrieve",
      title: 'QoS Profiles',
      path: 'qos-profiles/v1/retrieve-qos-profiles',
      body: '{"device": {"phoneNumber": "+541130124057"}}',
      displayName: "Retrieve QoS Profiles",
      description: "List QoS profiles available for a device",
      usecase: 'qosProfiles',
      versionId: 'qos-profiles/v1',
      scopes: ['dpv:FraudPreventionAndDetection#qos-profiles', 'qos-profiles:read'],
    },
    {
      name: "qosProfilesGet",
      title: 'QoS Profiles',
      path: 'qos-profiles/v1/qos-profiles/{profileName}',
      body: '',
      method: 'GET',
      displayName: "Get QoS Profile",
      description: "Retrieve a QoS profile by name",
      usecase: 'qosProfiles',
      versionId: 'qos-profiles/v1',
      scopes: ['dpv:FraudPreventionAndDetection#qos-profiles', 'qos-profiles:read'],
    },
    {
      name: "otpSendCode",
      title: 'One Time Password SMS',
      path: 'one-time-password-sms/v1/send-code',
      body: '{"phoneNumber": "+543462641443","message": "Your verification code is {{code}}"}',
      displayName: "Send Code",
      description: "Sends an OTP by SMS. The message must include {{code}}.",
      usecase: 'oneTimePasswordSms',
      versionId: 'one-time-password-sms/v1',
      scopes: ['dpv:FraudPreventionAndDetection#one-time-password-sms', 'one-time-password-sms:send-validate'],
    },
    {
      name: "otpValidateCode",
      title: 'One Time Password SMS',
      path: 'one-time-password-sms/v1/validate-code',
      body: '{"authenticationId": "","code": "123456"}',
      displayName: "Validate Code",
      description: "Validates an OTP using the authenticationId from send-code.",
      usecase: 'oneTimePasswordSms',
      versionId: 'one-time-password-sms/v1',
      scopes: ['dpv:FraudPreventionAndDetection#one-time-password-sms', 'one-time-password-sms:send-validate'],
    },
    {
      name: "smsShortMessage",
      title: 'SMS',
      path: 'sms/v0alpha1/short-message',
      body: '{"to": ["+543462641443"],"from": "+541141832256","content": "Hello from OpenXpand","category": "SERVICE"}',
      displayName: "Short Message",
      description: "Sends an SMS. Category: PROMOTION, SERVICE or TRANSACTION.",
      usecase: 'sms',
      versionId: 'sms/v0alpha1',
      scopes: ['dpv:FraudPreventionAndDetection#sms', 'sms:short-message:create'],
    },
    {
      name: "smsDeliveryCreate",
      title: 'SMS Delivery Notifications',
      path: 'sms-delivery-notification-subscriptions/v0alpha1/subscriptions',
      body: '{"subscriptionDetail": {"senderId": "AD-HDFCBK","type": "org.camaraproject.sms.v0.sms-delivery-status"},"subscriptionExpireTime": "2026-12-31T23:59:59Z","subscriptionMaxEvents": 100,"webhook": {"notificationUrl": "https://endpoint.example.com/sink","notificationAuthToken": "example-token"}}',
      displayName: "Create Subscription",
      description: "Creates a subscription for SMS delivery status notifications.",
      usecase: 'smsDeliveryNotifications',
      versionId: 'sms-delivery-notification-subscriptions/v0alpha1',
      scopes: ['dpv:FraudPreventionAndDetection#sms-delivery-notification-subscriptions', 'sms-delivery-notification-subscriptions:subscriptions:create'],
    },
    {
      name: "smsDeliveryGet",
      title: 'SMS Delivery Notifications',
      path: 'sms-delivery-notification-subscriptions/v0alpha1/subscriptions/{subscriptionId}',
      body: '',
      method: 'GET',
      displayName: "Get Subscription",
      description: "Retrieves an SMS delivery notification subscription by ID.",
      usecase: 'smsDeliveryNotifications',
      versionId: 'sms-delivery-notification-subscriptions/v0alpha1',
      scopes: ['dpv:FraudPreventionAndDetection#sms-delivery-notification-subscriptions', 'sms-delivery-notification-subscriptions:subscriptions:read'],
    },
    {
      name: "smsDeliveryDelete",
      title: 'SMS Delivery Notifications',
      path: 'sms-delivery-notification-subscriptions/v0alpha1/subscriptions/{subscriptionId}',
      body: '',
      method: 'DELETE',
      displayName: "Delete Subscription",
      description: "Deletes an SMS delivery notification subscription by ID.",
      usecase: 'smsDeliveryNotifications',
      versionId: 'sms-delivery-notification-subscriptions/v0alpha1',
      scopes: ['dpv:FraudPreventionAndDetection#sms-delivery-notification-subscriptions', 'sms-delivery-notification-subscriptions:subscriptions:delete'],
    },
  ];

export const steps = [
    {
      title: "Step 1:",
      description: "Authorization code request (GET: user-side)",
      url: `:host/auth/realms/:tenant/protocol/openid-connect/auth?response_type=code&client_id=:clientId&redirect_uri=https://openxpand-kc.vercel.app/api/callback&scope=:scope&prompt=none`,
      method: "GET"
    },
    {
      title: "Step 2:",
      description: "Token request with authorization code (POST: client-side)",
      url: `:host/auth/realms/:tenant/protocol/openid-connect/token`,
      method: "POST",
      headers: 'Content-Type: application/x-www-form-urlencoded',
      body: `grant_type=authorization_code&code=:code&redirect_uri=https://openxpand-kc.vercel.app/api/callback&client_id=:clientId&client_secret=:clientSecret`,
    },
];
